eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
server:
  port: 10001
spring:
  application:
    name: zuul
##配置zuul网关
zuul:
  routes:
    api-a:
      path: /member-zuul/**
      service-id: memeber-service
    api-b:
      path: /order-zuul/**
      service-id: order-service
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000